# Generated by Django 4.0.3 on 2022-03-20 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('glucose_value', models.IntegerField()),
            ],
        ),
    ]
